functionsDirectory = "/Users/marcus/Documents/code/spirits-studio/backend/netlify/functions"
functionsDirectoryOrigin = "config-v1"
plugins = []
headers = []
redirects = []

[build]
publish = "/Users/marcus/Documents/code/spirits-studio/backend"
publishOrigin = "default"
commandOrigin = "config"
command = "npm install"
functions = "/Users/marcus/Documents/code/spirits-studio/backend/netlify/functions"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]

[functions]

[functions."*"]
included_files = ["src/**"]
node_bundler = "esbuild"